<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns:fb="http://www.facebook.com/2008/fbml">
  <head>
    <title>Mytcg Trading Card Games</title>
    <link rel="icon" href="favicon.ico" />
    <script type="text/javascript" src="jquery/jquery-1.6.1.min.js"></script>
    <script type="text/javascript" src="jquery/jquery-ui-1.8.13.custom.min.js"></script>
    <script type="text/javascript" src="jquery/jquery.jscrollpane.min.js"></script>
    <script type="text/javascript" src="jquery/jquery.mousewheel.js"></script>
    
    <link href="css/stylesheet.css" type="text/css" rel="stylesheet" media="all"  />
    <link href="css/jquery.jscrollpane.css" type="text/css" rel="stylesheet" media="all" />
    <link rel="stylesheet" type="text/css" href="ui/jquery-ui-1.8.13.custom.css" />
    <script language="Javascript">
    $(document).ready (function(){
    	$('.divSigninText').jScrollPane();
    	
    	$("#back").click(function(){
    		window.location="signup.php";
    	});
    });
    </script>
    <style>
    	div{
    		position: absolute;
    	}
    	body{
		  font-size:10px;
		  font-family:Arial,Sans;
		  line-height:12px;
		  margin:0;
		  background-color:#C6C6C6;
		  color:#FFF;
		}
    </style>
  </head>
  <body>
      <div class="divPageLogin">
        <div class="divSignin"></div>
        <div class="divSign"><span>Terms</span> and conditions</div>
        <div class="divSigninText" style="top:190px;height:300px;">
        	<h2>TERMS  OF USE</h2>
<p>Welcome to the MYTCG Pty Ltd (&quot;<strong>MYTCG</strong>&quot;, &quot;<strong>We</strong>&quot;,  &quot;<strong>Our</strong>&quot;) mobile device  software application (the &quot;<strong>Application</strong>&quot;),  Web site, and any other mobile or web services or applications owned,  controlled, or offered by MYTCG (collectively, the &quot;<strong>MYTCG</strong><u> </u><strong>Services</strong>&quot;).  Subscribers, customers, users, and others who download, access, use, purchase  and/or subscribe to the MYTCG Services (collectively or individually &quot;<strong>You</strong>&quot; or &quot;<strong>Users</strong>&quot;) must do so under the following terms and conditions of  use.</p>
<p>This  Document describes the terms on which you may access and use the MYTCG  services, the website and application and governs the respective covenants  thereto. In order to become an MYTCG user, you must carefully read and accept  all of the terms and conditions of this document and the Privacy Policy. If  these conditions are inconsistent with the terms in this Terms of Use document,  these Terms of Use will apply. Nothing in this Agreement shall be deemed to  confer any third-party rights or benefits. If you do not agree to be bound by  the terms of this Agreement, you may not use nor access our services. <br />
  By  downloading, accessing, browsing, and or using the MYTCG Services, you  acknowledge that you have read, understood, and agree to be bound by all  consents and disclosures set forth in the MYTCG registration process (and  hereby incorporated herein by this reference), all of the following terms and  conditions, including any future modification to this terms of services, and  all guidelines (collectively, the “<strong>Agreement</strong>”).  If you do not agree to this agreement, then please cease using the MYTCG  Services immediately.</p>
<p>We  reserve the right to modify this Agreement at any time, and without prior  notice, by posting amended terms on the Website. Your continued use of the MYTCG  service indicates your acceptance of the amended User Agreement. </p>
<h2>IMPORTANT DISCLAIMERS</h2>
<p>You acknowledge and agree that MYTCG has offered the MYTCG  Services, set its prices, and entered into this agreement in reliance upon the  warranty disclaimers and the limitations of liability set forth below. You  further acknowledge and agree that the warranty disclaimers and the limitations  of liability set forth in this agreement reflect a reasonable and fair  allocation of risk between you and MYTCG, and that the warranty disclaimers and  the limitations of liability set forth in this agreement form an essential  basis of the bargain between you and MYTCG. MYTCG would not be able to provide  the MYTCG Services to you on an economically reasonable basis without these  limitations and disclaimers.</p>
<h2>PRIVACY</h2>
<p>Your  privacy is very important to us. To better protect your rights we have provided  the MYTCG Privacy Policy to explain our privacy practices in detail. Please  review our Privacy Policy below, which also governs your visit to our Website,  as well as the conditions of its use including the Application. In the event of  any inconsistency between the MYTCG Privacy Policy and this Terms of Use  Agreement, the Terms of Use Agreement shall apply. <br />
  You  will own your data and your data will remain at all times your responsibility.  You may be required to disclose or allow access to part of your data in order  to use the Service.</p>
 <h2> MEMBERSHIP  ELIGIBILITY</h2>
 <p>You  must be old enough to enter into a binding legal obligation. These Terms of Use  are a binding Agreement between you and MYTCG. By using the MYTCG service you  represent that you are old enough to enter into a legal obligation and are  agreeing to these Terms of Use. You must have the legal rights in your account  for the purpose of any fee or charges required by the Service. <br />
  The  MYTCG Service is not available to any users suspended or removed from the  system by us for any reason and in our sole discretion. Additionally, users are  prohibited from selling, trading, or otherwise transferring their account or  application to another party. If you do not qualify, you may not use the MYTCG  Service. <br />
  You  must obtain at all time an eligible E-mail address and update your E-mail  address at the Web-site in the event you change your E-mail address.</p>
<h2>USE  OF SERVICE</h2>
<p>Your  use of the MYTCG service is governed by this Agreement. MYTCG may refuse  service without prior notice to any user for any or no reason. In the event you  terminate your Membership, de-register from the Service or your account is  terminated by MYTCG, all your data will be erased from the Web-site.</p>
<p>The MYTCG Services are not available  to any Users suspended or removed from the MYTCG Services by MYTCG. You agree  that the information you provide to MYTCG upon registration and at all other  times will be true, accurate, current and complete. You also agree that you  will ensure that this information is kept accurate and up to date at all times.  For example, you should notify MYTCG if your mobile device number changes.</p>
<p><strong>YOUR  USE OF THE SERVICE INVOLVES THE TRANSMISSION OF DATA TO AND FROM YOUR MOBILE  PHONE, WHICH MAY BE SUBJECT TO CARRIER DATA CHARGES. REVIEW YOUR WIRELESS PLAN  BEFORE USING THE SERVICE. MYTCG WILL NOT BE RESPONSIBLE FOR ANY DATA CHARGES  INCURRED IN CONNECTION WITH THE MYTCG SERVICE.</strong></p>
<p>You  are responsible for maintaining the confidentiality of your password and  account, and are fully responsible for all activities that occur under your  password or account with or without your knowledge. If you knowingly provide  your login and password information to another person, your account privileges  may be suspended temporarily or terminated. You agree to immediately notify MYTCG  of any unauthorized use of your password or account or any other breach of  security. MYTCG cannot and will not be liable for any loss or damage arising  from your failure to comply with this section.</p>
<h2>USER  CONDUCT AND ONLINE BEHAVIOR</h2>
<p>You  understand and agree that your use of the MYTCG Services or any engagement you  have or will have with MYTCG, is strictly intended not to include certain  conducts which are defined herein as prohibited by MYTCG, and any such use  shall be considered a breach of this Agreement, thus granting MYTCG the right  to immediately terminate this Agreement and your user status and pursue any  other right or remedy allowed by law.</p>
<p>Please  exercise respect when participating in any of MYTCG's community features such  as forums, blogs, email functions, etc. (if so applicable and as might be  altered from time to time), and when using file transfer or any other feature  of the MYTCG Services. </p>
 <p>The  prohibited conduct you hereby agree to abide shall include but is not limited  to the following: </p>
<ol start="1" type="1">
  <li>Posting of       content or initiation of communications which are unlawful, defamatory,       abusive, offensive, racist, obscene, pornographic, discriminatory, an       invasion of privacy, harmful to a minor or otherwise infringement on any       intellectual property rights of a third party or would otherwise violate       the rights of any third party. </li>
  <li>The MYTCG Services for any commercial or       non-private use, it being understood that the MYTCG Services are for       personal, non-commercial use only. </li>
  <li>Fail to deliver payment for the MYTCG       Services. </li>
  <li>Use the       Service for any illegal purpose, including but not limited to conspiring       to violate laws. </li>
  <li>Falsely       state, impersonate, or otherwise misrepresent your identity, including but       not limited to the use of a pseudonym, or misrepresenting your current or       previous positions and qualifications, or your affiliations with a person       or entity, past or present. </li>
  <li>Upload,       post, email, transmit or otherwise make available any content or initiate       communications which include information that you do not have the right to       disclose or make available under any law or under contractual or fiduciary       relationships (such as insider information, or proprietary and       confidential information learned or disclosed as part of employment       relationships or under nondisclosure agreements). </li>
  <li>Use the MYTCG Service in connection with       hazardous environments requiring fail-safe performance or any application       in which the failure or inaccuracy of that application or the MYTCG       Services could lead directly to death, personal injury, or severe physical       or property damage. </li>
  <li>Upload,       post, email, transmit or otherwise make available any content or initiate       communication that infringes upon patents, trademarks, trade secrets,       copyrights or other proprietary rights. </li>
  <li>Upload,       post, email, transmit or otherwise make available any material that       contains software viruses or any other computer code, files or programs       designed to interrupt, destroy or limit the functionality of any computer       software or hardware or telecommunications equipment. </li>
  <li>Forge       headers or otherwise manipulate identifiers in order to disguise the       origin of any communication transmitted through the MYTCG service. </li>
  <li>Interfere       with or disrupt the MYTCG Service or servers or networks connected to the MYTCG       Service, or disobey any requirements, procedures, policies or regulations       of networks connected to the MYTCG Service. </li>
  <li>Make any       commercial use of the Web-site, Web-site content, Service or Software. </li>
  <li>Hack or in       any way harm the Web-Site or the Service. </li>
  <li>Attempt to       reverse engineer, decompile or disassemble the MYTCG service, software or       any portion thereof, nor otherwise attempt to create or derive the source       code. </li>
  <li>Attempt to gain unauthorized access to       the MYTCG Services, or any part of it, other accounts, computer systems or       networks connected to the MYTCG Services, or any part of it, through       hacking, password mining or any other means or interfere or attempt to       interfere with the proper working of the MYTCG Services or any activities       conducted on the MYTCG Service. </li>
  <li>Sell or transfer or allow another person       to access your account password or MYTCG Services account. </li>
</ol>
<h2>INTERNATIONAL  USE</h2>
 <p> Recognizing  the global nature of the Internet, you agree to comply with all applicable  local rules including but not limited to rules regarding online conduct and  acceptable content. Specifically, you agree to comply with all applicable laws  regarding the transmission of technical data exported from the country in which  you reside.</p>
<h2>INFORMATION  PROVIDED</h2>
<p>You  understand that by posting materials on the MYTCG service or otherwise  providing materials to MYTCG, you are granting to MYTCG a royalty-free,  perpetual, irrevocable license to use this information in the course of  offering the MYTCG service. Furthermore, you understand that MYTCG retains the  right to reformat, excerpt, or translate any materials submitted by you. You agree that MYTCG may collect and use technical and related  information, including but not limited to technical information about your  computer, system and application software, and peripherals, that is gathered  periodically by the MYTCG Software to facilitate the provision of services,  software updates, product support and other services to you (if any) related to  the MYTCG Software and to verify compliance with the terms of this Agreement. MYTCG  may use this information in accordance with the terms of its, Privacy Policy,  as long as it is in a form that does not personally identify you. You understand that all information  publicly posted or privately transmitted through the MYTCG Service is the sole  responsibility of the person from which such content originated and that MYTCG  will not be liable for any errors or omissions in any content. You understand  that MYTCG cannot guarantee the identity of any other users with whom you may  interact in the course of using the MYTCG Service. Additionally, we cannot  guarantee the authenticity of any data which users may provide about themselves  or relationships they may describe.</p>
<p>You  understand that MYTCG cannot guarantee the completeness of any data which you  provide or synchronize with the Service.</p>
<h2>ACCESS  TO SERVICE</h2>
<p>Use  of manual or automated software, devices, or other processes to  &quot;crawl&quot; or &quot;spider&quot; any web pages contained in the MYTCG  Website is strictly prohibited. You agree not to monitor or copy, or allow  others to monitor or copy, our web pages, the application or the content  included herein. You also agree not to &quot;frame&quot; or otherwise simulate  the appearance or function of this Website or Application. Furthermore, you  agree not to take any action that interferes with the proper working of or  places an unreasonable load on our infrastructure, including but not limited to  unsolicited communications, attempts to gain unauthorized access, or  transmission or activation of computer viruses.</p>
<h2>MYTCG  ELECTRONIC COMMUNICATIONS</h2>
<p>When  you visit the MYTCG Website or Application or send e-mails to us, you are communicating  with MYTCG electronically. In the course of providing you services, MYTCG may  need to communicate with you via email and or SMS and or the Application or by  posting notices on this Website. You agree to receive emails which are specific  to your account and necessary for the normal functioning of the MYTCG Service  and periodical emails that update you on recent news and events related to the MYTCG  service, including a series of welcome emails which help inform new users about  various features of the MYTCG Service. You also agree to have your name and/or  email address listed in the header of certain communications which you initiate  through the MYTCG Service. You further agree that all agreements, notices,  disclosures and other communications that we provide to you electronically  satisfy any legal requirement that such communications be in writing.</p>
<h2>WEBSITE  LINKS</h2>
<p>Within  the context of the MYTCG service, MYTCG may provide links to other websites  that we feel are relevant and interesting to our users (&quot;<strong>Link Sites</strong>&quot;).  MYTCG is not responsible for the content on the Link Sites and is not  responsible for the accuracy of the information and intellectual property  notices therein. Some of these Link Sites may provide you with opportunities to  purchase products (&quot;<strong>Products</strong>&quot;). We do not endorse any of the  Products nor do we make any representations or warranties in connection with  the Products.</p>
<p>When you click on one of these  links, you are 'clicking' to another Web site. MYTCG does not accept liability  for misuse of any information by any Web site controller to which we may link.  We encourage you to read the privacy statements of these linked sites, which  may differ from ours.</p>
<p>In addition, if you take advantage  of an offer from one of our partners, you may be providing information directly  to that partner. We encourage you to review the privacy statements of these  partners.</p>
<h2>TRADEMARKS</h2>
<p>The  MYTCG name and logo, and other graphics, logos, page headers, button icons,  scripts, and service names are trademarks, registered trademarks or trade dress  of MYTCG in all countries. You agree not to use MYTCG's trademarks and trade  dress in connection with any product or service that is not the MYTCG or MYTCG  Services, in any manner that is likely to cause confusion among customers, or  in any manner that disparages or discredits the MYTCG services. All other  trademarks not owned by MYTCG that appear on the Website are the property of  their respective owners, who may or may not be affiliated with, connected to,  or sponsored by MYTCG.</p>
<h2>COPYRIGHT</h2>
<p>All  content included on this Website and Application, such as text, graphics,  logos, button icons, images, audio clips, digital downloads, data compilations,  and software, is the property of MYTCG or its content suppliers and protected  by international copyright laws. The compilation of all content on this Website  and Application is the exclusive property of MYTCG and protected by  international copyright laws. All software used is the property of MYTCG or its  software suppliers and protected by international copyright laws.</p>
<h2>PATENTS</h2>
<p>One  or more patents or pending-patents owned by MYTCG might apply to this Website  and Application and to the features and services accessible via the Website and  Application. Some portions of this Website and Application might operate under  license of one or more patents.</p>
<h2>NOTIFICATION  OF COPYRIGHT INFRINGEMENT</h2>
<p>Immediately  upon receipt of notice, MYTCG will investigate complaints relating to potential  copyright infringement and take appropriate actions if so required by the  applicable laws. If you believe that your work has been used or copied in a way  that constitutes copyright infringement and such infringement is occurring on  this Website or on Link Sites, please notify MYTCG immediately.</p>
<p>A  notification of claimed infringement must be a written communication addressed  to the designated agent as set forth below, and must include substantially all  of the following: (i) a physical or electronic signature of the person  authorized to act on behalf of the owner of the copyright interest that is  alleged to have been infringed; (ii) a description of the copyrighted work or  works that you claim have been infringed (&quot;<strong>infringed work</strong>&quot;)  and identification of what material in such work(s) is claimed to be infringing  (&quot;<strong>infringing work</strong>&quot;) and which you request to be removed or  access to which is to be disabled; (iii) a description of where the material  that you claim is infringing is located on the Website; (iv) information  sufficient to permit MYTCG to contact you, such as your telephone number, and  email address; (v) a statement by you that you have a good faith belief that  the use of the material identified in your Notice in the manner complained of  is not authorized by the copyright owner, its agent, or the law; (vi) a  statement by you that the information in your Notice is accurate and, under  penalty of perjury that you are the copyright owner or authorized to act on the  copyright owner's behalf.</p>
<h2>MONITORING  AND ENFORCEMENT</h2>
<p>MYTCG  reserves the right at its sole discretion to monitor activities and content  associated with the MYTCG Services, but it not obligated in any way to do so or  to provide any assurance as to the nature of these activities and content.  Furthermore, MYTCG does not undertake to have the ability to, control or  actively monitor content and therefore does not guarantee its accuracy,  integrity or quality. You acknowledge and agree that in the process of using  our Website and Application you may be exposed to content that you find  offensive or objectionable, and that this exposure might be the cause of  variation between community standards, incompliance by certain individuals with  our policies and practices and the like, all being situation which might be  outside MYTCG's reach. If such situations arise, we would kindly ask you to  promptly contact our Customer Service Department to let us know of content that  you find objectionable. MYTCG may investigate the complaints and violations of  our policies that come to our attention and may take any action that MYTCG  believes is appropriate, including, but not limited to issuing warnings,  removing the content or terminating accounts and/or subscriptions. However, due  to the great variation between situations and interpretations, You acknowledge  and agree of MYTCG's right at its sole discretion not to take any action. Under  no circumstances will MYTCG be liable in any way for any content, including,  but not limited to, any errors or omissions in any content, or any loss or  damage of any kind incurred as a result of the use of, access to, or denial of  access to any content on the Website and Application.</p>
<p>MYTCG does not control the content of  User accounts and does not have any obligation to monitor such content for any  purpose. You acknowledge that you are solely responsible for all content and  material that you provide to the MYTCG Services.</p>
<h2>USER DATA</h2>
<p>The MYTCG Services may allow the submission of content and  materials (such as contact lists, messages, photos, videos, or notes) by you  (&quot;<strong>User</strong><u> </u><strong>Data</strong>&quot;), and the hosting, storing,  sharing and/or publishing of such User Data. You shall be solely responsible  for your own User Data and the consequences of storing or transmitting them.<p>
  MYTCG assumes no responsibility whatsoever in connection with or  arising from User Data. MYTCG assumes no responsibility for actively monitoring  User Data for inappropriate or illegal content. If at any time MYTCG chooses,  in its sole discretion, to monitor User Data, MYTCG nonetheless assumes no  responsibility for the content of the User Data, no obligation to modify or  remove any inappropriate User Data, and no responsibility for the conduct of  the User submitting User Data. Further, MYTCG does not endorse and has no  control over the content of User Data submitted by other Users. MYTCG makes no  warranties, express or implied, as to the content of User Data or the accuracy  and reliability of the storage of any User Data. Nonetheless, MYTCG reserves  the right to prevent you from submitting User Data and to, restrict or remove  User Data for any reason at any time.</p>
<h2>INDEMNIFICATION</h2>
<p>By  accepting this User Agreement, you agree to indemnify and otherwise hold  harmless MYTCG, its officers, employees, agents, subsidiaries, affiliates,  co-branders, other partners and employees from any direct, indirect,  incidental, special, consequential or exemplary damages resulting from (a) your  use of the MYTCG Service; (b) unauthorized access to or alteration of your  communications with or through the MYTCG Service; or (c) any claim or demand,  including reasonable attorneys' fees, made by any third party due to or arising  out of content you submit, post to or transmit through the Website and or  Application, your use of the Website and or Application, your connection to the  Site and or Application, your violation of the Terms of Use, or your violation  of any rights of another person or entity. Any business transactions which may  arise between users from their use of the MYTCG service are the sole  responsibility of the users involved.</p>
<p>Without  limitation of the terms and conditions set forth in our Privacy Policy, you  understand and agree that MYTCG may disclose personally identifiable  information if required to do so by law or in the good faith belief that such  disclosure is reasonably necessary to comply with legal process, enforce this  User Agreement, or protect the rights, property, or safety of the MYTCG  service, MYTCG, its users, and the public.</p>
<h2>WARRANTIES  AND DISCLAIMERS</h2>
<p>Except  as expressly provided otherwise in a written agreement between you and MYTCG,  you acknowledge and agree that the MYTCG Services are provided on an &quot;as  is&quot; and &quot;as available&quot; basis and without warranties of any kind  either expressed or implied. You further acknowledge and agree that MYTCG does  not assume any responsibility for prompt or proper delivery, or retention of  any user information or communications between users. MYTCG assumes no  responsibility for the accuracy or existence of any communications between  users. To the fullest extent permissible pursuant to applicable law, MYTCG hereby  expressly disclaims all warranties of any kind, whether express or implied,  including, but not limited to the implied warranties of merchantability,  fitness for a particular purpose and non-infringement.</p>
<p>MYTCG  makes no warranty that (i) the MYTCG service will meet your requirements, (ii)  the MYTCG service will be uninterrupted, timely, secure, or error-free, (iii)  the results that may be obtained from use of the MYTCG service will be accurate  or reliable, (iv) the quality of any products, services, information, or other  material purchased or obtained by you through the MYTCG service will meet your  expectations, and (v) any errors in the software will be corrected.</p>
<p>Any  material downloaded and software installed or otherwise obtained through the  use of the MYTCG service is done at your own discretion and risk and that you  will be solely responsible for any damage to your computer system or loss of  data that results from the download of any such material. </p>
<p>No  advice or information, whether oral or written, obtained by you from MYTCG or  through or from the MYTCG service shall create any warranty not expressly  stated in this user agreement.</p>
<p>Some  jurisdictions do not allow the exclusion of certain warranties or the  limitation or exclusion of liability for incidental or consequential damages.  Accordingly, some of the above limitations may not apply to you.</p>
<h2>END USER LICENSES</h2>
<p>To use the MYTCG  Software you must have a mobile device that is compatible with the MYTCG  Services. MYTCG does not warrant that the MYTCG Services will be compatible  with your device.</p>
<p><strong>License Grant.</strong> MYTCG hereby grants you a  non-exclusive, non-transferable, revocable license to use a compiled code copy  of the MYTCG Software as follows: You may use the MYTCG Software for one MYTCG  Services subscription account (a &quot;Subscription Account&quot; is comprised  of the shared resources accessible by a single login ID) on up to two mobile  devices legally under your control, for your personal use. You will retain all  ownership rights in User Data that you transfer to MYTCG for data protection.  When you submit User Data to MYTCG, you hereby grant to MYTCG, a non-exclusive,  royalty-free, worldwide license to use, copy, modify, sublicense, and  distribute your User Data on and through the Service (e.g., organizing into  folders) on your behalf solely for the purpose of providing the data protection  service. You represent and warrant that: (i) you own all right, title and  interest in your User Data or otherwise have the right to grant the license set  forth herein, and (ii) the submission of your User Data on or through the  service does not (and will not) violate the privacy rights, publicity rights,  copyrights, contract rights or any other rights of any person. You agree to pay  all royalties, license fees and any other monies owning any person by reason of  any User Data posted by you on or through the Service. You will be solely  liable for any damage resulting from any infringement of copyrights,  trademarks, or other proprietary rights or any other harm resulting from any  User Data.</p>
<p><strong>Restrictions.</strong> You may not: (i) modify, disassemble,  decompile or reverse engineer the MYTCG Software, except to the extent that  such restriction is expressly prohibited by law; (ii) rent, lease, loan,  resell, sublicense, distribute or otherwise transfer the MYTCG Software to any  third party or use the MYTCG Software to provide time sharing or similar  services for any third party; (iii) make any copies of the MYTCG Software; (iv)  remove, circumvent, disable, damage or otherwise interfere with  security-related features of the MYTCG Software, features that prevent or  restrict use or copying of any content accessible through the MYTCG Software,  or features that enforce limitations on use of the MYTCG Software; or (v)  delete the copyright and other proprietary rights notices on the MYTCG  Software.</p>
<p><strong>Software  Upgrades.</strong> You acknowledge  that MYTCG may from time to time issue upgraded versions of the MYTCG Software,  and may automatically electronically upgrade the version of the MYTCG Software  that you are using on your mobile device. You consent to such automatic  upgrading on your mobile device, and agree that the terms and conditions of  this Agreement will apply to all such upgrades.</p>
<p><strong>Rights Reserved.</strong> The foregoing license grant under  this Agreement is not a sale of the MYTCG Software or any copy thereof and MYTCG  or its third party partners or suppliers retain all right, title, and interest  in the MYTCG Software (and any copy thereof). Any attempt by you to transfer  any of the rights, duties or obligations hereunder, except as expressly  provided for in this Agreement, is void. MYTCG reserves all rights not  expressly granted under this Agreement.</p>
<h2>ENTIRE  AGREEMENT</h2>
<p>The  User Agreement constitutes the entire agreement between you and MYTCG and governs  your use of the MYTCG Services.</p>
<h2>UPDATES  TO THE AGREEMENT</h2>
<p>MYTCG  may update or change these Terms of Use from time to time and recommends that  you review the Terms of Use on a regular basis. You can review the most current  version of the Terms of Use at any time at <a href="http://www.impi.net">www.mytcg.net</a>. If MYTCG makes a change to the Terms  of Use, it will post the revised Terms of Use on our website at the link as  herein noted. You understand and agree that your continued use of the MYTCG  Service after the Terms of Use has changed constitutes your acceptance of the  Terms of Use as revised. Without limiting the foregoing, if MYTCG makes a  change to the Terms of Use that materially impacts your use of the Service, MYTCG  may post notice of any such change on our website and/or email you notice of  any such change to your MYTCG account.</p>
<h2>LIMITATION  OF LIABILITY</h2>
<p>You  expressly understand and agree that under no circumstances MYTCG shall be  liable for any direct, indirect, incidental, special, consequential or  exemplary damages, including but not limited to, damages for loss of profits,  goodwill, use or the inability to use, data and materials or other intangible  losses (even if MYTCG has been advised of the possibility of such damages)  relating to the MYTCG Services, the MYTCG web site, the MYTCG software or any  other service related to MYTCG and damage to your computer or cellular device  caused by install or use of plug-ins (software) downloaded from the MYTCG web  site. Some jurisdictions do not allow the exclusion of the limitation or  exclusion of liability for incidental or consequential damages. Accordingly,  some of the above limitations may not apply to you. No advice or information,  whether written or oral, obtained by you from MYTCG or from or through the MYTCG  web site or Application shall create any warranty not expressly stated in the  terms of use.</p>
<h2>TERMINATION</h2>
<p>You  agree that MYTCG may, with or without cause, immediately terminate your MYTCG  account and access to the MYTCG Service without prior notice. Without limiting  the foregoing, MYTCG will have the right to cause the termination of a certain  user's use of the MYTCG Service, at any of the following conditions: (a)  breaches or violations of this Agreement or other incorporated agreements or  guidelines, (b) requests by law enforcement or other governmental authorities,  (c) a request by you, as a user of the MYTCG services (self-initiated account  deletions), (d) unexpected technical issues or problems, and (e) extended  periods of inactivity. Termination of your MYTCG account includes removal of  access to all offerings within the MYTCG Service and may also bar you from  further use of the MYTCG Service. Furthermore, you agree that all terminations  shall be made in MYTCG’s sole discretion and that MYTCG shall not be liable to  you nor any third-party for any termination of your account or access to the MYTCG  Service. </p>
<h2>IN THE EVENT OF MERGER, SALE, OR BANKRUPTCY</h2>
<p>In the event that MYTCG is  acquired by or merged with a third party entity, we reserve the right, in any  of these circumstances, to transfer or assign the information we have collected  from our Users as part of such merger, acquisition, sale, or other change of  control so that the MYTCG Service can continue operations. In the unlikely  event of our bankruptcy, insolvency, reorganization, receivership, or  assignment for the benefit of creditors, or the application of laws or  equitable principles affecting creditors' rights generally, we may not be able  to control how your personal information is treated, transferred, or used. You  will be notified via notice through the MYTCG Services of any such change in  ownership or control of your personally identifiable information.</p>
<h2>GOVERNING  LAW AND JURISDICTION</h2>
<p>This  Agreement between you and MYTCG shall be governed by and construed according to  the laws of the Republic of South Africa, without regard to the conflict of  laws provisions thereof. Any dispute arising under or in relation to this  Agreement shall be resolved exclusively in the competent court located in Cape  Town, South-Africa, and each of the parties hereby irrevocably submits to the  exclusive jurisdiction of such courts.</p>
<p><strong>Severability, Waiver.</strong> If any provision of this Agreement shall be unlawful, void, or for any reason  unenforceable, then that provision shall be limited or eliminated to the  minimum extent necessary so that this Agreement shall otherwise remain in full  force and effect and enforceable. A provision of this Agreement may be waived  only by a written instrument executed by the party entitled to the benefit of  such provision. The failure of any party at any time to require performance of  any provision of this Agreement shall in no manner affect such party's right at  a later time to enforce the same. A waiver of any breach of any provision of  this Agreement shall not be construed as a continuing waiver of other breaches  of the same or other provisions of this Agreement.</p>
<p><strong>Headings; Entire Agreement.</strong> The heading references herein are for convenience purposes only, do not  constitute a part of this Agreement and shall not be deemed to limit or affect  any of the provisions hereof. This is the entire agreement between us relating  to the subject matter herein and shall not be modified except in writing,  signed by both parties, or by a change to this Agreement made by MYTCG as set  forth above.</p>
<p><strong>Claims.</strong> You and MYTCG agree that any  cause of action arising out of or related to the MYTCG services must commence  within one (1) year after the cause of action accrues. Otherwise, such cause of  action is permanently barred.</p>
<h2>PRIVACY POLICY</h2>
<p>IMP  Pty Ltd. (&quot;<strong>MYTCG</strong>&quot;) values the privacy of our customers,  users, and others who use the mobile phone application, www.myTCG.net, and  other web sites, services, and content owned or operated by  MYTCG and the MYTCG service are committed to  protecting your privacy. This Privacy Notice details important  information regarding the use and disclosure of User information collected  through the MYTCG Services. MYTCG provides this Privacy Notice to help you make  an informed decision about whether to use or continue using the MYTCG Services. By accessing the Website or the  Service, you are consenting to the information collection and use practices  described in this privacy statement.</p>
<p>In  this Privacy Policy, all references to &quot;<strong>you</strong>&quot; shall mean the  user using the Services. Accordingly, all references to &quot;<strong>we</strong>&quot;  shall mean MYTCG.</p>
<h2>COLLECTION  OF YOUR PERSONAL INFORMATION</h2>
<p>We  might approach you when we need information that personally identifies you (&quot;<strong>Personal Information</strong>&quot;) or allows us to contact you to  provide a service or carry out a transaction that you have requested such as  receiving information about the Service or MYTCG, entering a contest, ordering  e-mail newsletters, joining a limited-access premium website or service,  signing up for an event or training, or when purchasing, downloading and/or  registering services offered by the Service or affiliated with the Services.</p>
<p>The  Personal Information we collect may include, but is not limited to, your name,  title, company or organization name, work email, work phone, work or home  address, information about your job function, information about your company,  and credit card information.</p>
<p>The  Services may collect certain information relating to your visit, such as the  name of the Internet Service Provider (ISP) and the Internet Protocol (IP)  address through which you access the Internet; the date and time you access the  Services; the pages that you access while at the Services and the internet  address of the website from which you linked directly to our Services, if  applicable. This information is used to help improve the Services, analyze  trends, and administer the Services.</p>
<h2>INFORMATION INCLUDES  BUT IS NOT LIMITED TO</h2>
<ul type="disc">
  <li>REGISTRATION INFORMATION:       You provide to MYTCG certain personally-identifiable information (such as       your mobile phone number, wireless carrier / operator, email address,       password, etc.) when choosing to subscribe to the MYTCG Services. </li>
  <li>BACKUP DATA:       If you choose to use the MYTCG Backup &amp; Sync feature, we will use the       data you provide to us for the backup service. This feature is optional. </li>
  <li>LOCATION INFORMATION:       If you choose to use the MYTCG AntiTheft feature, we will derive location       information from your wireless carrier, certain third-party service       providers, or directly from the mobile device that is used with the MYTCG       Services. </li>
  <li>LOG FILE INFORMATION:       When you use the MYTCG Services, our servers automatically record certain       information about your usage from your mobile device and web browser.       These server logs may include information such as IMEI/equipment       identification number, IMSI/subscriber identification number, mobile phone       number, device type and manufacturer, operating system type and version,       wireless carrier / operator, network type, country of origin, web       requests, Internet Protocol (&quot;IP&quot;) address, browser type,       browser language, referring / exit pages and URLs, platform type, time       zone, user agent, number of clicks, domain names, landing pages, pages       viewed and the order of those pages, features used in the MYTCG mobile       application, the amount of time spent on particular web pages, the dates       and times of your requests, and one or more cookies that may uniquely       identify your browser. </li>
</ul>
<h2>USE  OF YOUR PERSONAL INFORMATION<a name="_GoBack" id="_GoBack"></a></h2>
<p>The  Personal Information collected during the use of the Services will be used to  operate the Services and to provide the services or carry out the transactions  you have requested or authorized. MYTCG uses your personally  identifiable and registration information and backup data (if applicable) and  location data (if applicable) to operate, maintain, and provide to you all of  the features and functionality of the MYTCG Service.</p>
<p>MYTCG uses your personally  identifiable and certain non-personally-identifiable information (such as  anonymous log file information) to track and analyze User preferences and  trends in order to improve the quality and design of the MYTCG Services and to  create new features, promotions, functionality, and services.</p>
<p>We  may use your Personal Information to provide you with important information  about the product or service that you are using, including updates and  notifications. Additionally, with your permission, we may send you information  about other products and services related to the Services, and/or share  information with MYTCG’s subsidiaries, affiliates and/or partners so they may  send you information about their products and services.</p>
<p>If you use the Backup &amp; Sync  feature of the MYTCG Services, MYTCG will store the backup data you provide. If  you delete backup data, we will retain that information for a short amount of  time to enable recovery in the event of accidental deletion. We also store  backup data for a reasonable amount of time after you close your account to allow  recovery if you reactivate your account.</p>
<p>We  might merge Services visitation data with anonymous demographic information for  research purposes, and we may use this information in aggregate to provide more  relevant content.</p>
<p>If you have use the MYTCG Services  with a mobile phone number and device, then MYTCG may send text messages to  your phone to communicate with your device and to provide download links.</p>
<p>When  you sign up for a newsletter or agree to receive promotional email, we may use  customized links or similar technologies to track e-mail links that you click.  We may associate that information with your Personal Information in order to  provide you more focused email communications or purchase information. Each  email communication includes an unsubscribe link allowing you to stop delivery  of that type of communication.</p>
<p>If you email MYTCG for support or  otherwise, or fill out a survey, we will retain that information to provide you  support and to improve the MYTCG Service.</p>
<p>We  might occasionally hire other companies to provide limited services on our  behalf. We shall only provide those companies the Personal Information needed  for them to effectively and efficiently deliver the service.</p>
<p>We  may disclose personal information if required to do so by law or in the good  faith belief that such action is necessary to (a) conform to the edicts of the  law or comply with legal process served on MYTCG or the Services; (b) protect  and defend the rights or property of MYTCG and the Services (as well as other MYTCG  &quot;family Services&quot;, if applicable); or (c) act in urgent circumstances  to protect the personal safety of MYTCG employees or agents, users of MYTCG  products or services, or members of the public.</p>
<p>Personal  Information collected on the Services may be stored and processed in the any  country in which MYTCG or its affiliates, subsidiaries or agents maintain  facilities, and by using the Services, you hereby give your consent to any such  transfer of Personal Information outside your country.</p>
<h2>CONTROL  OF YOUR PERSONAL INFORMATION</h2>
<p>MYTCG does not share your personally  identifiable information or personally identifiable location-information with  other, third-party companies for their commercial or marketing use without your  express consent or unless you have opted-in to be part of a specific program or  feature in accordance with the applicable MYTCG Services consent procedures.</p>
<p>Except  as otherwise described in this statement, personal information you provide on  the Website and Application will not be shared outside of MYTCG and its  controlled subsidiaries, affiliates and partners without your permission.</p>
<p>Please  be aware that this privacy statement and any choices you make on the Services  will not necessarily apply to Personal Information you may have provided to MYTCG  in the context of other, separately operated, products or services.</p>
<p>MYTCG  may send out periodic emails informing you of technical service or security  issues related to a product or service you requested, or confirming you  requested a product or service. In some services offered by MYTCG, contact with  the customer is an intrinsic part of the service. You will not be able to  choose to unsubscribe to these mailings, as they are considered an essential  part of the service(s) you have chosen.</p>
<p>Some  services offered may collect information that is not accessible via the account  profile. However, in such cases, you might be able to access your Personal  Information by contacting MYTCG as described at the bottom of this statement,  or through alternative means of access described on the Website.</p>
<h2>SECURITY  OF YOUR PERSONAL INFORMATION</h2>
<p>MYTCG  is committed to protecting the security of your Personal Information. We use a  variety of security technologies and procedures to help protect your personal  information from unauthorized access, use, or disclosure. For example, we store  the Personal Information you provide on computer servers with limited access  that are located in controlled facilities. Additionally, when we transmit  sensitive Personal Information (such as a credit card number) over the  Internet, we protect it through the use of encryption, such as the Secure  Socket Layer (SSL) protocol and the like.</p>
<p>MYTCG uses commercially reasonable  physical, managerial, and technical safeguards. We cannot, however, ensure or  warrant the security of any information that MYTCG receives on your behalf to operate  the MYTCG Services or that you transmit to MYTCG and you do so at your own  risk. We also cannot guarantee that such information may not be accessed,  disclosed, altered, or destroyed by breach of any of our physical, technical,  or managerial safeguards.</p>
<p>If MYTCG learns of a security  systems breach, then we may attempt to notify you electronically so that you  can take appropriate protective steps. MYTCG may post a notice on the MYTCG  Services if a security breach occurs. Depending on where you live, you may have  a legal right to receive notice of a security breach in writing.</p>
<h2>PROTECTION  OF CHILDREN'S PERSONAL INFORMATION</h2>
<p>MYTCG  is a general audience website and application and does not knowingly collect  any Personal Information from children.</p>
<h2>USE  OF COOKIES</h2>
<p>We  might use cookies on this Service to ensure the integrity of the registration  process and to personalize the Services. A cookie is a small text file that is  placed on your hard disk by a web page server. Cookies cannot be used to run  programs or deliver viruses to your computer. Cookies are uniquely assigned to  you, and can only be read by a web server in the domain that issued the cookie  to you.</p>
<p>MYTCG may use both session cookies and  persistent cookies. A session cookie disappears after you close your browser. A  persistent cookie remains after you close your web browser and may be used by  us during your subsequent visits to the MYTCG Web site. Persistent cookies set  by the MYTCG Web site can be removed. Please review your web browser  &quot;Help&quot; file to learn the proper way to modify your cookie settings.</p>
<p>Web  beacons, also known as clear gif technology or action tags, may be used to  assist in delivering the cookie on our site. This technology is a tool we use  to compile aggregated statistics about usage of the Services, such as how many  visitors clicked on key elements (such as links or graphics) on the Website  page or a newsletter. We may share aggregated website statistics with partner  companies but do not allow other companies to place clear gifs or cookies on  our websites unless there is a temporary, overriding customer value (such as  merging into the Website a website that relies on third-party cookies or clear  gifs).</p>
<p>Please  note you have the ability to accept or decline cookies. Most web browsers  automatically accept cookies, but you can usually modify your browser setting  to decline cookies if you prefer. Nonetheless, if you choose to decline  cookies, you may not be able to fully experience the interactive features of  this Service or other web sites you visit.</p>
<h2>ENFORCEMENT  OF THIS PRIVACY STATEMENT, QUESTIONS AND COMMENTS</h2>
<p>If  you have questions regarding this statement, you should contact <u>support@mytcg.net</u></p>
<h2>CHANGES  TO THIS STATEMENT</h2>
<p>We  may occasionally update this privacy statement. When we do, we will also revise  the &quot;last updated&quot; date at the top of the privacy statement. For  material changes to this privacy statement, MYTCG will make effort to notify  you either by placing a prominent notice on the home page of our Website,  amending the date of first abovementioned of this statement, or by directly  sending you a notification. We encourage you to periodically review this  privacy statement to stay informed about how we are helping to protect the  Personal Information we collect. Your continued use of the service constitutes  your agreement to this privacy statement and any updates. </p>

        </div>
        <div id="txtResponse" class="profileResponse" style="display:none;height:16px;top:488px;left:670px;"><img src="_site/loading51.gif" width="15" height="15" /></div>
        <div id="back" class="divSigninEnter" style="width:140px;top:510px;left:575px;">Back to Signup page</div>
      </div>
  </body>
</html>